### ISSUE TITLE
Unable to load xlm-mlm-100-1280 after init_model succeeds

### ISSUE THREAD

**Issue by jarib** [explosion/spacy-transformers#102]
Even though the `init_model` script appears to succeed, the model is not loadable:

```
$ python examples/init_model.py --lang xx --name xlm-mlm-100-1280 ./xlm-100
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
ℹ Creating model for 'xlm-mlm-100-1280' (xx)
✔ Initialized the model pipeline
✔ Saved 'xlm-mlm-100-1280' (xx)
Pipeline: ['sentencizer', 'trf_wordpiecer', 'trf_tok2vec']
Location: ./xlm-100
✔ Model loads!
```

```console
$ python
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('./xlm-100')
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/util.py", line 217, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/util.py", line 262, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/language.py", line 940, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/language.py", line 935, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 227, in spacy.pipeline.pipes.Pipe.from_disk
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "pipes.pyx", line 218, in spacy.pipeline.pipes.Pipe.from_disk.load_model
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 362, in from_bytes
    layer.from_bytes(weights[i])
  File "/Users/jari/src/spacy-transformers/spacy_transformers/wrapper.py", line 264, in from_bytes
    self._model.load_state_dict(torch.load(filelike, map_location=map_location))
  File "/Users/jari/src/spacy-transformers/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for XLMModel:
	size mismatch for embeddings.weight: copying a param with shape torch.Size([200000, 1280]) from checkpoint, the shape in current model is torch.Size([30145, 1280]).
```

**Comment by svlandeg** [comment]
I noticed that `xlm-mlm-100-1280` has a `vocab.json` instead of a `vocab.txt`, maybe that's related?

**Comment by svlandeg** [comment]
I'll go ahead and close this issue as the library has been significantly rewritten and published today as v. 1.0 🥳 

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions). Thanks!
