### ISSUE TITLE
Transformers-Compatibility Issue with SerializableDistilBertTokenizer

### ISSUE THREAD

**Issue by JulianGerhard21** [explosion/spacy-transformers#117]
spacy-transformers: 0.5.1
transformers: 2.3.0

Hi,

today I wanted to follow [HuggingFace's DistilBERT](https://github.com/huggingface/transformers/tree/master/examples/distillation) for the german pretrained model. Following [this reply from @ines ](https://github.com/explosion/spacy-transformers/issues/81) I downloaded the `vocab.txt`, `distilbert-base-german-cased-pytorch_model.bin` and the `bert_config.json`, executed the `init_model.py` and got the following result:

```
(ea_env) C:\Users\xx\PycharmProjects\word_embeddings\pretrained_models>python init_model.py --lang de --name distilbert-base-german-cased distilbert-base-german-cased
ℹ Creating model for 'distilbert-base-german-cased' (de)
✔ Initialized the model pipeline
✔ Saved 'distilbert-base-german-cased' (de)
Pipeline: ['sentencizer', 'trf_wordpiecer', 'trf_tok2vec']
Location: distilbert-base-german-cased
✔ Model loads!
```

which looks good. Loading the model in spacy by providing the absolute path to spacy.load("..."), no error is thrown. However if I want to parse a sentence with Spacy, the following error occurs:

```
>>> parsed_sentence = nlp(sentence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy\language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\wordpiecer.py", line 50, in __call__
    pieces = self.predict([doc])
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\wordpiecer.py", line 93, in predict
    seg_words = self.model.tokenize(segment.text)
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\transformers\tokenization_utils.py", line 656, in tokenize
    if self.init_kwargs.get('do_lower_case', False):
AttributeError: 'SerializableDistilBertTokenizer' object has no attribute 'init_kwargs'
```

As far as I have read, DistilBERT is natively supported by the `transformers` library thus it should be by `spacy-transformers` or am I wrong? Now I have seen, that a requirement for spacy-tranformers is transformers <2.1.0. Do you think the error is related to a version conflict?

Regards and merry christmas
Julian

**Comment by svlandeg** [comment]
Have you tried running the exact same code with e.g. `transformers==2.0.0` ?

**Comment by svlandeg** [comment]
Ok I could confirm the bug is present also with `transformers==2.0.0`.
It looks like a few crucial fields are not being serialized by the `SerializableDistilBertTokenizer` - submitting a PR with a fix.

**Comment by JulianGerhard21** [comment]
Hi @svlandeg ,

thanks for testing it and submitting a solution here aswell as in NER branch. Ill test both today and give you Feedback! 

Regards 
Julian

**Comment by JulianGerhard21** [comment]
Hi @svlandeg,

I can confirm that your [PR](https://github.com/explosion/spacy-transformers/pull/121) fixes the problem, however, another one occurs:

```
  File "<stdin>", line 1, in <module>
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy\language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\tok2vec.py", line 105, in __call__
    outputs = self.predict([doc])
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\tok2vec.py", line 160, in predict
    return self.model.predict(docs)
  File "C:\Users\\Envs\eva_env\lib\site-packages\thinc\neural\_classes\model.py", line 133, in predict
    y, _ = self.begin_update(X, drop=None)
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy_transformers\model_registry.py", line 408, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
  File "C:\Users\\Envs\eva_env\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy_transformers\model_registry.py", line 310, in get_features_forward
    sent_seg_ids = get_segment_ids(transformers_name, *seg_lengths)
  File "C:\Users\\Envs\eva_env\lib\site-packages\spacy_transformers\util.py", line 286, in get_segment_ids
    raise ValueError(f"Unexpected model name: {name}")
ValueError: Unexpected model name: distilbert-base-german-cased
```

After investigating this, I observed that unlike `roberta`, `xlnet` and others, there is no `get_distilbert_segment_ids` method in the `util.py` of the library. I added this likewise the corresponding BERT one - now everything works.

I assumed that the segment ID computation in BERT format is the same for DistilBERT. 

I am now able to package and install the model in a spaCy-esque way.

**Comment by svlandeg** [comment]
Ah, yes! We recently fixed that issue with the segment IDs: https://github.com/explosion/spacy-transformers/pull/119

I was working of the main branch (from source) so already had that fix ;-)
