### ISSUE TITLE
Alignment error while Training NER with feature/spacy-v3 in spacy-transformers

### ISSUE THREAD

**Issue by aishwarya-agrawal** [explosion/spacy-transformers#192]
Hi, I have been trying to train NER with spacy-transformers
command: 
`spacy train-from-config train_path dev_path config_path -o output_path`
It seems to be training for shorter length file where say 200 lines are tagged. But doesn't when passing longer file.

Getting the following error
```Traceback (most recent call last):
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/__main__.py", line 29, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/cli/train_from_config.py", line 164, in train_from_config_cli
    raw_text=raw_text,
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/cli/train_from_config.py", line 186, in train_from_config
    nlp.begin_training(lambda: corpus.train_examples)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/language.py", line 679, in begin_training
    get_examples, pipeline=self.pipeline, sgd=self._optimizer, **kwargs
  File "spacy/syntax/nn_parser.pyx", line 643, in spacy.syntax.nn_parser.Parser.begin_training
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/ml/tb_framework.py", line 41, in init
    tok2vec = model.get_ref("tok2vec").initialize(X=X)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/projects/cypher-ner/spacy-transformers/spacy_transformers/layers/transformer_model.py", line 65, in init
    tensors = model.layers[0].predict(token_data)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/model.py", line 297, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/layers/pytorchwrapper.py", line 79, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 729, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/transformers/modeling_bert.py", line 174, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
Can someone help me in understanding what I am missing here

**Comment by aishwarya-agrawal** [comment]
when the length of sentence is shorter:
getting following error for some files
```
Traceback (most recent call last):
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/__main__.py", line 29, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/cli/train_from_config.py", line 164, in train_from_config_cli
    raw_text=raw_text,
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/cli/train_from_config.py", line 186, in train_from_config
    nlp.begin_training(lambda: corpus.train_examples)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/language.py", line 685, in begin_training
    get_examples, pipeline=self.pipeline, sgd=self._optimizer, **kwargs
  File "spacy/syntax/nn_parser.pyx", line 643, in spacy.syntax.nn_parser.Parser.begin_training
  File "/home/aishwarya/projects/ner/thinc/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/anaconda3/envs/spacy_transformers_env/lib/python3.6/site-packages/spacy/ml/tb_framework.py", line 41, in init
    tok2vec = model.get_ref("tok2vec").initialize(X=X)
  File "/home/aishwarya/projects/ner/thinc/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/projects/ner/thinc/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/aishwarya/projects/ner/thinc/thinc/model.py", line 281, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/aishwarya/projects/ner/thinc/thinc/layers/chain.py", line 90, in init
    curr_input = layer.predict(curr_input)
  File "/home/aishwarya/projects/ner/thinc/thinc/model.py", line 297, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/aishwarya/projects/ner/spacy-transformers/spacy_transformers/layers/trfs2arrays.py", line 25, in forward
    dst, get_d_src = apply_alignment(model.ops, trf_data.align, src)
  File "/home/aishwarya/projects/ner/spacy-transformers/spacy_transformers/align.py", line 45, in apply_alignment
    Y = Ragged(X[indices], cast(Ints1d, ops.asarray(align.lengths)))
IndexError: index 356 is out of bounds for axis 0 with size 355
```

**Comment by svlandeg** [comment]
The `feature/spacy-v3` branch is work in progress, and requires a (non-published) version of spaCy v.3 (from the `develop` branch). While we're happy to take feedback on this early work & merge bug fixes if you find them, we can't really provide support at this point as the code base is not stable and it's going to be difficult for us to replicate your exact setting. As soon as we have dev releases out, this should be more doable.

BTW - your error msg does remind me of a bug I think I tried fixing a few weeks ago, so this may already be addressed.

**Comment by aishwarya-agrawal** [comment]
Yeah, I did see the fix in a PR here `https://github.com/explosion/spacy-transformers/pull/173`, and I am using the required branches like feature/spacy-v3 and spacy develop. I was still getting error. But yeah it's better to wait for a stable release. I will also look out for the fix if I can.

Thanks for the response.

**Comment by svlandeg** [comment]
It took us a bit longer than we'd hoped, but we recently did publish a [pre-release](https://pypi.org/project/spacy-nightly/3.0.0rc1/) of spaCy v3 and a `v1.0.0rc0` version of `spacy-transformers`. You should now be able to run [`spacy train`](https://nightly.spacy.io/api/cli#train) with a [config file](https://nightly.spacy.io/usage/training#config) which can refer to a [`Transformer`](https://nightly.spacy.io/api/transformer) component as part of any component's `tok2vec` layer. More docs here: https://nightly.spacy.io/usage/embeddings-transformers

I hope you get a chance to try this out - let us know how you go or if you run into specific issues!
