### ISSUE TITLE
Cupy error with loading transformers model with RC

### ISSUE THREAD

**Issue by timothyjlaurent** [explosion/spacy-transformers#256]
## How to reproduce the behavior

I installed spacy-nightly and the latest rc of spacy-transformers.

If I do a training run with transformer config like:

```toml
[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v1"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"
[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "bert-base-uncased"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

```

I've seen this happen with `bert-base-uncased` and with `funnel-transformer/small`.

I'm running with 

```
/home/jovyan/ve/bin/python -m spacy train configs/config-transformer.cfg --output training/ --paths.train corpus/cies_training.spacy --paths.dev corpus/cies_eval.spacy --gpu-id 0
```
and seeing this error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy/cli/_util.py", line 65, in setup_cli
    command(prog_name=COMMAND)
  File "/home/jovyan/ve/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/ve/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/ve/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/ve/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/ve/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/ve/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy/training/initialize.py", line 67, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy/language.py", line 1240, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 334, in initialize
    self.model.initialize(X=docs)
  File "/home/jovyan/ve/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy_transformers/layers/transformer_model.py", line 111, in init
    tensors = model.layers[0].predict(wordpieces)
  File "/home/jovyan/ve/lib/python3.8/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/jovyan/ve/lib/python3.8/site-packages/thinc/layers/pytorchwrapper.py", line 79, in forward
    Xtorch, get_dX = convert_inputs(model, X, is_train)
  File "/home/jovyan/ve/lib/python3.8/site-packages/spacy_transformers/layers/transformer_model.py", line 168, in _convert_transformer_inputs
    if tokens.token_type_ids:
  File "cupy/core/core.pyx", line 1040, in cupy.core.core.ndarray.__nonzero__
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

## Info about spaCy

- **spaCy version:** 3.0.0rc5
- **Platform:** Linux-5.4.0-1035-aws-x86_64-with-glibc2.10
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_trf (3.0.0a1)
* Operating System:
Ubuntu 18.04 Docker base - on Pytorch cuda image
* Python Version Used:
3.8.5
* spaCy Version Used:
```
# pip freeze

en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0a1/en_core_web_trf-3.0.0a1.tar.gz
spacy-alignments @ file:///home/jovyan/.cache/pypoetry/artifacts/a2/7c/b6/ff53035570b21d9341ac35a2fa663f1605e569b673cb5a5440b8884ac4/spacy_alignments-0.7.2-cp38-cp38-manylinux2014_x86_64.whl
spacy-legacy @ file:///home/jovyan/.cache/pypoetry/artifacts/98/71/16/2babd753f2d61470cb58c20519db632b6084ca1a33d21ad6808ac4655c/spacy_legacy-3.0.0-py2.py3-none-any.whl
spacy-nightly @ file:///home/jovyan/.cache/pypoetry/artifacts/93/c4/ad/c926c4c4348972607602df8de7140b5c14dd6ba26bcc38e425771286c4/spacy_nightly-3.0.0rc5-cp38-cp38-manylinux2014_x86_64.whl
spacy-transformers @ file:///home/jovyan/.cache/pypoetry/artifacts/8e/a3/5f/ff5b3368088b62d9f1e737e67094f29d3d5a5304d05a1c7e081a8b698b/spacy_transformers-1.0.0rc3.dev0-py2.py3-none-any.whl

# pip freeze | grep cupy
cupy-cuda110 @ file:///home/jovyan/.cache/pypoetry/artifacts/00/94/61/1de878dd1b47ae1a1e0372debfc10e3cfb17f9158e9a96fb161c0d8da8/cupy_cuda110-9.0.0b1-cp38-cp38-manylinux1_x86_64.whl
(ve
```

* Environment Information:

**Comment by timothyjlaurent** [comment]
installing from master solves this.
