### ISSUE TITLE
RoBERTa: RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by tsoernes** [explosion/spacy-transformers#51]
Nvidia Driver Version: 418.40.04    CUDA Version: 10.1 
spacy                      2.1.8           
spacy-pytorch-transformers 0.3.0     
Python 3.7
Not running in jupyter/colab
This only happens with RoBERTa; not BERT
```
package   en-pytt-robertabase-lg       en_pytt_robertabase_lg       2.1.0   ✔
```

```
File /home/ubuntu/fintechdb/nlp/catml/textcat/train_pytt.py, line 106, in main
    nlp.update(texts, cats, sgd=optimizer, drop=dropout, losses=losses)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy_pytorch_transformers/language.py, line 98, in update
    docs, drop=drop, **component_cfg.get("pytt_tok2vec", {})
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy_pytorch_transformers/pipeline/tok2vec.py, line 129, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy_pytorch_transformers/model_registry.py, line 347, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py, line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy_pytorch_transformers/model_registry.py, line 276, in apply_model_to_batches
    return model.begin_update(inputs, drop=drop)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy_pytorch_transformers/wrapper.py, line 98, in begin_update
    y_var = self._model(**model_kwargs)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py, line 547, in __call__
    result = self.forward(*input, **kwargs)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_roberta.py, line 173, in forward
    return super(RobertaModel, self).forward(input_ids, token_type_ids, attention_mask, position_ids, head_mask)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py, line 715, in forward
    head_mask=head_mask)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py, line 547, in __call__
    result = self.forward(*input, **kwargs)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py, line 437, in forward
    layer_outputs = layer_module(hidden_states, attention_mask, head_mask[i])
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py, line 547, in __call__
    result = self.forward(*input, **kwargs)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py, line 417, in forward
    intermediate_output = self.intermediate(attention_output)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py, line 547, in __call__
    result = self.forward(*input, **kwargs)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py, line 389, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py, line 142, in gelu
    return x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))

RuntimeError: CUDA error: device-side assert triggered
File cupy/cuda/driver.pyx, line 211, in cupy.cuda.driver.moduleUnload                                                                                                                

File cupy/cuda/driver.pyx, line 91, in cupy.cuda.driver.check_status

CUDADriverError: CUDA_ERROR_ASSERT: device-side assert triggered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 211, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 91, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ASSERT: device-side assert triggered
File cupy/cuda/driver.pyx, line 211, in cupy.cuda.driver.moduleUnload

File cupy/cuda/driver.pyx, line 91, in cupy.cuda.driver.check_status
```

**Comment by svlandeg** [comment]
Hi @tsoernes, apologies that we never got back to you.

In the meantime, this library has been significantly rewritten and published today as v. 1.0. We'll publish the corresponding spaCy v. 3.0 very soon as well. The combined result should hopefully provide a much more robust user experience. I hope you'll give it another spin!

I'll close this for now, but new bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
