### ISSUE TITLE
get_features_forward IndexError: list index out of range

### ISSUE THREAD

**Issue by JulianGerhard21** [explosion/spacy-transformers#64]
**OS**: Windows 10
**Spacy**: 2.1.8
**PYTT**: 0.4.0

Currently, after using your finetuned script, I am experiencing the following error while using a packaged model in a rasa pipeline (which is shown by the first block), however I think the problem lies somewhere in block2:

```
Traceback (most recent call last):
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JulianGerhard\AppData\Local\Programs\Python\Python36\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\cli\train.py", line 75, in train
    kwargs=extract_additional_arguments(args),
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\train.py", line 89, in train_async
    kwargs,
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\train.py", line 176, in _train_async_internal
    kwargs=kwargs,
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\train.py", line 225, in _do_training
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\train.py", line 443, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\train.py", line 80, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 195, in train
    updates = component.train(working_data, self.config, **context)
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\utils\spacy_utils.py", line 155, in train
    attribute_docs = self.docs_for_training_data(training_data)
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\utils\spacy_utils.py", line 146, in docs_for_training_data
    docs = [doc for doc in self.nlp.pipe(texts, batch_size=50)]
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\utils\spacy_utils.py", line 146, in <listcomp>
    docs = [doc for doc in self.nlp.pipe(texts, batch_size=50)]
  File "c:\users\juliangerhard\appdata\local\programs\python\python36\lib\site-packages\spacy\language.py", line 751, in pipe
    for doc in docs:


  File "c:\python\python36\lib\site-packages\spacy\language.py", line 751, in pipe
    for doc in docs:
  File "pipes.pyx", line 941, in pipe
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\spacy\util.py", line 463, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\spacy_pytorch_transformers\pipeline\tok2vec.py", line 120, in pipe
    outputs = self.predict(docs)
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\spacy_pytorch_transformers\pipeline\tok2vec.py", line 162, in predict
    return self.model.predict(docs)
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\thinc\neural\_classes\model.py", line 133, in predict
    y, _ = self.begin_update(X, drop=None)
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\spacy_pytorch_transformers\model_registry.py", line 347, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "c:\users\\appdata\local\programs\python\python36\lib\site-packages\spacy_pytorch_transformers\model_registry.py", line 236, in get_features_forward
    assert isinstance(sents[0], Span)
IndexError: list index out of range
```
The process until this point worked without errors, the model gets properly installed. I have downgraded to pytt version 0.3.0 but that didn't help.

Any clues about this?

**Comment by mikkelam** [comment]
How did you end up handling the empty strings?

**Comment by pmbaumgartner** [comment]
For more context, I get this error training with with `en_trf_robertabase_lg`, but not `en_trf_distilbertbaseuncased_lg`.

**Comment by mikkelam** [comment]
pretty sure this is related to how the model is able to encode documents that are just empty strings `''`

**Comment by MartinoMensio** [comment]
Having the same issue when doing the following:

```python
import spacy
nlp = spacy.load('en_trf_bertbaseuncased_lg')
nlp('')
```

The other models (`en_core_XXX` handle empty string documents without problems, so it would be nice to see uniformity also for the transformer models.

I tried to put the assertion in a conditional statement https://github.com/explosion/spacy-transformers/blob/master/spacy_transformers/model_registry.py#L289

```python
if len(sents):
    assert isinstance(sents[0], Span)
```

But in this way the exception is then raised by the `transformers` library:

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/pipeline/tok2vec.py", line 105, in __call__
    outputs = self.predict([doc])
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/pipeline/tok2vec.py", line 160, in predict
    return self.model.predict(docs)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 133, in predict
    y, _ = self.begin_update(X, drop=None)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/model_registry.py", line 409, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/model_registry.py", line 338, in apply_model_to_batches
    return model.begin_update(inputs, drop=drop)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/wrapper.py", line 96, in begin_update
    return self.predict(inputs), lambda dY, sgd=None: None
  File "/Users/mm35626/KMi/experiments/spacy-transformers/spacy_transformers/wrapper.py", line 85, in predict
    y_var = self._model(**model_kwargs)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 627, in forward
    pooled_output = self.pooler(sequence_output)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mm35626/KMi/experiments/spacy-transformers/venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 373, in forward
    first_token_tensor = hidden_states[:, 0]
IndexError: index 0 is out of bounds for dimension 1 with size 0
```

because it expects at least a token but we have a doc with zero sents and tokens. I don't know the library `thinc` but the issue should be in the `spacy_transformers.model_registry.foreach_sentence` method that should shortcut the model for the docs that don't have sentences https://github.com/explosion/spacy-transformers/blob/master/spacy_transformers/model_registry.py#L400-L412

**Comment by nsorros** [comment]
> ```python
> nlp = spacy.load('en_trf_bertbaseuncased_lg')
> ```

Just for reference, I also run into this problem lately with a production bert system in a slighly more weird case. As far as I understand spacy-transformers splits the text into batches internally to pass to the transformer. If the split ends up containing only spaces then this error is thrown.

It is worth saying that it is difficult to replicate the behaviour in this case as you pass in documents and then spacy separately batches those so for example passing documents one by one does not throw an error, it greatly depends on passing the exact documents in the same order in to get the same batch of only spaces. So debugging this leaves you scratching your head.

I think a check can be added when propagating spaces only texts to transformers, I am happy to work on that, if such a check sounds reasonable.

**Comment by adrianeboyd** [comment]
I know I spent an afternoon trying to get empty docs not to fail in v0.6.x and gave up in the end. There are so many brittle edge cases across the model types that it's very frustrating. (It's not a problem in the rewritten v1.0, though!)

We're not going to spend much more development time on v0.6.x ourselves, but we wouldn't be opposed to a PR, either. In general, we'd recommend having a look at spacy v3 + spacy-transformers v1 for transformer pipelines. It's all much easier to configure and much less brittle.

**Comment by nsorros** [comment]
> I know I spent an afternoon trying to get empty docs not to fail in v0.6.x and gave up in the end. There are so many brittle edge cases across the model types that it's very frustrating. (It's not a problem in the rewritten v1.0, though!)
> 
> We're not going to spend much more development time on v0.6.x ourselves, but we wouldn't be opposed to a PR, either. In general, we'd recommend having a look at spacy v3 + spacy-transformers v1 for transformer pipelines. It's all much easier to configure and much less brittle.

Good to hear, we have a PR open to migrate to v3 actually which is almost there. Makes sense not spending more time in 0.6, thanks for the update.
