### ISSUE TITLE
NER WIP: ValueError: could not broadcast input array from shape (10,10) into shape (10,64)

### ISSUE THREAD

**Issue by JulianGerhard21** [explosion/spacy-transformers#97]
**Spacy**: 2.2.2
**Thinc**: 7.3.1
**spacy-transformers**: 0.5.0/feature/ner
**Python**: 3.6.8
**Model**: de_trf_bertbasecased_lg

Hi,

the finetuning/training process ends successfull after modifying the samples sentences to german. The entities are properly printed afterwards. If `output_dir` is specified and the script tries to load the model, the following error with full stacktrace occurs:

```
Traceback (most recent call last):
  File "bert_finetuner_splitset.py", line 324, in <module>
    plac.call(main)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "bert_finetuner_splitset.py", line 64, in main
    nlp = spacy.load(model)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\util.py", line 215, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\util.py", line 236, in load_model_from_package
    return cls.load(**overrides)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\de_trf_bertbasecased_lg_ner\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\util.py", line 279, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\util.py", line 262, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\language.py", line 940, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\util.py", line 733, in from_disk
    reader(path / key)
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\spacy\language.py", line 935, in <lambda>
    p, exclude=["vocab"]
  File "nn_parser.pyx", line 663, in spacy.syntax.nn_parser.Parser.from_disk
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\thinc\neural\_classes\model.py", line 376, in from_bytes
    copy_array(dest, param[b"value"])
  File "C:\Users\JulianGerhard\Envs\ner_env\lib\site-packages\thinc\neural\util.py", line 145, in copy_array
    dst[:] = src
ValueError: could not broadcast input array from shape (10,10) into shape (10,64)
```

What can be done here?

Regards

**Comment by JulianGerhard21** [comment]
I just read [this post for prodigy](https://support.prodi.gy/t/could-not-broadcast-input-array-from-shape-96-into-shape-128/1441/2) and thought I should mention, that I downloaded the model with the current spacy version.

TYPE      NAME                      MODEL                     VERSION
package   de-trf-bertbasecased-lg   de_trf_bertbasecased_lg   2.2.0     ✔

**Comment by honnibal** [comment]
Could you try v0.5.1? I think it might be fixed.

**Comment by JulianGerhard21** [comment]
Hi @honnibal 

I tried that by first merging the 0.5.1 `master` branch into the `feature/ner` (since installing that one told me that it was version 0.5.0). During the merge `tok2vec` and `model_registry` needed to be merged manually. After doing that with a "best-guess" strategy (taking the feature/ner content mostly), I retrained and the error still occurs. 

Feel free to ask for more tests if useful for you.

Regards

**Comment by svlandeg** [comment]
Perhaps this is a similar issue as the one in Issue #105 and which PR #120 aims to address.

@JulianGerhard21 : can you provide the content of the `meta.json` file in your `output` directory (specifically the `factories` part near the end)?
